### ISSUE TITLE
Prepare onboarding to DSH for CHIMERA

### ISSUE THREAD

**Issue by docsteveharris** [UCL-Chimera/bellerophon#22]
- [x] share generic DSH onboarding process (needs linking)
- [x] define roles that include upload/download @skeating 
- [ ] borrow and SOP for joiners and leavers from CCHIC (ask Claire) @docsteveharris 
- [ ] prep a summary document as per notes above

**Comment by docsteveharris** [comment]
Document in place https://github.com/UCL-Chimera/bellerophon/blob/main/DataSafeHaven/Getting%20an%20account%20on%20DSH.md

**Comment by docsteveharris** [comment]
roles prob mean nothing more than

- access
- upload rights
- downloads right

**Comment by clairejblack** [comment]
This is all covered in the Accessing CHIMERA Data in the UCL Data Safe Haven document

**Comment by docsteveharris** [comment]
steve to review; claire's done the work

**Comment by docsteveharris** [comment]
closing this as I don't think it helps
