### ISSUE TITLE
Documentation to record anon decision making

### ISSUE THREAD

**Issue by docsteveharris** [UCL-Chimera/bellerophon#23]
- contact Tim R 
  - key difference is we need to link non-OMOP data before we export
- contact Mai
  - ask about help with the actual anon
  - ask about help with verification

- constrain first pass work to _just_ blood gas data as per Sam's existing request
- then do a first pass

We have 2 weeks of Sarah's time in Q1 2023

Current actions

- [x] steve to continue soft follow-up with May and Tim R
- [x] Moh and Dan to share an SOP or similar from GOSH so we can check we're aligned
- [ ] ~Sarah to prepare first pass anon as per ethics protocol~

**Comment by docsteveharris** [comment]
I checked in with Tim Roberts here at UCLH.
They do not have a specific anonymisation process in place for OMOP-ES.
So I think we continue with our own ad-hoc/bespoke one for now, and then regroup as we move forwards and this becomes a regular 'thing'

**Comment by docsteveharris** [comment]
pretty much there
remaining step is to figure out how to document the decisions
perhaps just save in the readme accompanying the file the decision, the reviewers etc

**Comment by skeating** [comment]
The SOP from GOSH is  [here](https://liveuclac-my.sharepoint.com/:b:/g/personal/cceasmk_ucl_ac_uk/EXYGHpHOpNJJtLt_srRwg3kB7FXUBmAfA1s24U5OWSlH4w?e=yzN9fAl)

**Comment by docsteveharris** [comment]
will prepare as part of #35

**Comment by docsteveharris** [comment]
basically a dup / already covered in #35
