### ISSUE TITLE
Blood gas data

### ISSUE THREAD

**Issue by docsteveharris** [UCL-Chimera/bellerophon#24]
This ticket tracks the 'completeness' of the data request
Requesters = Gevic and Alex

Initial description (via @samiranray )

- pH
- paCO2
- paO2
- SaO2
- p50 (as calculated by the blood gas analyser)
- Temperature (ideally co-incident but whatever measured temperature there is in the EPIC flowsheets)
- FHbF (probably irrelevant in adult population so may be missing in the blood gas data)
- FMetHb
- FCOHb
- Lactate
- Minute volume (measured)
- Phosphate
- Blood transfusion (just time rather than volume) (not available but theoretically in prep with the blood transfusion theme)
- Diagnosis label (I used very broad categories - respiratory, sepsis, neurology)

Suggest we partition this list into those which are 1:1 straightforwards and the rest which should be separate issues

**Comment by docsteveharris** [comment]
This is not specific enough
We need help from @aasiyah and @clairejblack to provide the relevant `concept_ids` so that Sarah can provide the extract

**Comment by clairejblack** [comment]
@skeating can yo just let me know which concept_ids you need.  Is this LOINC/SNOMED and/or the EPIC Row ID

**Comment by skeating** [comment]
thanks @clairejblack I need the SNOMED ID number

**Comment by clairejblack** [comment]
@skeating have added a file with the easy ones. Still working on where transfusions are. Please let me know if the fields are not populated.

**Comment by docsteveharris** [comment]
Data not yet been passed through to the OMOP-ES so impossible to assess whether it's correct

**Comment by clairejblack** [comment]
Just found out there has been an EPIC change freeze. None of the mapping changed required to add the remaining ABG items have happened and probably wont until  the end of March.

**Comment by docsteveharris** [comment]
Need to keep the Epic source field as some of the mapping is too abstract
Claire to add in

We think that there are 27 measurements of which 3 are missing
Sarah to follow-up and see if fixed.

**Comment by skeating** [comment]
@clairejblack IGNORE MY EMAIL
This is missing data

From hic_cc_003

BG concepts

No measurements for

45537652 | Blood Transfusion (Without reported   diagnosis)

----------------
From hic_cc_003

Twin lung concepts

No measurements for

4119048 | Inspiratory/expiratory ratio (attribute)

4230167 | Artificial respiration

**Comment by clairejblack** [comment]
@skeating I think this is mostly complete except the Blood transfusions and the morbidities which are in the condition_occurence table. I am not sure if we just want to pull the specific ones @samiranray wants or all of them. perhaps we can discuss

**Comment by skeating** [comment]
@clairejblack looking at getting modifier_source_value This is horrible as the only thing that can be used to join is time.

Question:

If  I have





![Image](https://github.com/UCL-Chimera/bellerophon/assets/1736558/cb5732c9-9f5e-478b-ab1c-46dbac22eb90)


does this mean at 08.28 the person came off the ventilator and went back on at 21.00 ??

**Comment by clairejblack** [comment]
I’m sure I managed a different join, but will have to go back and look. Unfortunately no, it is not reliable, If they have an ETT which hasn’t been removed then it might, But you would expect it to tbe replaced by something else. Generally it means it just hasn’t been complted in the HER.
Sorry!

From: Sarah Keating ***@***.***>
Date: Monday, 12 June 2023 at 08:53
To: UCL-Chimera/bellerophon ***@***.***>
Cc: Black, Claire ***@***.***>, Mention ***@***.***>
Subject: Re: [UCL-Chimera/bellerophon] Define blood gas data request (Issue #24)

⚠ Caution: External sender


@clairejblack<https://github.com/clairejblack> looking at getting modifier_source_value This is horrible as the only thing that can be used to join is time.

Question:

If I have

[Image removed by sender. Image]<https://user-images.githubusercontent.com/1736558/245068644-cb5732c9-9f5e-478b-ab1c-46dbac22eb90.png>

does this mean at 08.28 the person came off the ventilator and went back on at 21.00 ??

**Comment by skeating** [comment]
@clairejblack if you can remember what you did join on that would be great because I cannot see anything that gives a clean join for each of the measurements.

**Comment by docsteveharris** [comment]
@skeating what's the join task? 
are you trying to create a table that describes the 'procedure' (ventilator) mode for the times that match the blood gas sample?
I don't think (but maybe I'm wrong) this _has_ to be your task. 
I'd drop the two tables separately into the ABG 'project' and let the CHIMERA folk (and future data scientists) decide how they want to do this.

**Comment by skeating** [comment]
@docsteveharris Yes I was trying to have a col in my measurements table that said what type of ventilator the person was on when the measurement was taken
but I can easily supply a table that gives you a list of times and dates with the person ID and a type of ventilator and let the people interested work it out for themselves

**Comment by docsteveharris** [comment]
Blocked by #36

**Comment by skeating** [comment]
Now unblocked and first 1000 patients data is in DSH
