### ISSUE TITLE
Additional items for Sam

### ISSUE THREAD

**Issue by docsteveharris** [UCL-Chimera/bellerophon#27]
@samiranray thinks there are some other low hanging fruit in terms of data items that would unlock other projects within CHIMERA
This ticket describes and documents what those items are
The team then will review / split and offer an feasibility as to what can be done this quarter and what's going to need more time.

**Comment by samiranray** [comment]
Additional data request:

For stats PhD (Ali Septiandri, co-supervisors @samiranray, Alex Diaz), in addition to the blood gas data for Victoria Volodina/Gevik Gregorian project, additional items
- iCa (blood gas)
- Na (blood gas)
- K (blood gas)
- bicarb (blood gas)
- base excess (blood gas)
- Cl (blood gas)
- Magnesium (labs)
- Albumin (labs)
- Urea (labs)
- end tidal CO2 (hourly)


@clairejblack @skeating Hope these are not difficult to identify...
