### ISSUE TITLE
Retroactive agreement for existing GOSH data

### ISSUE THREAD

**Issue by docsteveharris** [UCL-Chimera/bellerophon#32]
Existing data from GOSH prev anon and used
We would now like to 'officially' migrate this into the CHIMERA share on the DSH
Need the agreement to make this so

**Comment by docsteveharris** [comment]
currently chasing turing (responded OK) but still waiting on GOSH

**Comment by docsteveharris** [comment]
no updates
need to chase for an update 
@samiranray : can you update when you have a chance please

**Comment by skeating** [comment]
The retroactive data will be covered by the new gosh agreement
