### ISSUE TITLE
Access to OMOP ES

### ISSUE THREAD

**Issue by docsteveharris** [UCL-Chimera/bellerophon#36]
Currently unable to access omop-reservoir-postgres_db-1 or uclvlddpragae06
Not clear why
@skeating following up with Baptiste
Claire and Steve also stuck

Loop claire and steve into email thread; follow-up to allow scriptable access

**Comment by docsteveharris** [comment]
we have confirmed 
- we can access from R
- we can access from GUI
not clear why python is misbehaving

**Comment by skeating** [comment]
Everything seems to be working now .
Can probably close @docsteveharris
