### ISSUE TITLE
[UCL-44] Demo CPET and EHR linkage

### ISSUE THREAD

**Issue by docsteveharris** [UCL-Chimera/bellerophon#39]
Nick Tetlow has access to CPET data
He is an NHS employee and therefore could also inspect the OMOP-ES product
We could therefore use this as an example of a pre-move merge such that we can add the CPET data with the correct identifier (pseudonymised) to the OMOP-ES data.

* [X] Nick Tetlow to have access to OMOP-ES / CCHIC (in the first instance)
* [ ] Next step would be to agree how to manage the identifiers for a merge (whilst anonymising) (see #31 )
* [x] sarah to add Nick to the UCLH CHIMERA share

<sub>From [SyncLinear.com](https://synclinear.com) | [UCL-44](https://linear.app/drstevok/issue/UCL-44/demo-cpet-and-ehr-linkage)</sub>

**Comment by docsteveharris** [comment]
written to Rich Clarke to give Nick access

**Comment by docsteveharris** [comment]
@docsteveharris to check in with Nick

**Comment by docsteveharris** [comment]
Nick and Sarah in contact
Nick getting access to DSH share for CHIMERA
Then we should do a scoping meeting to plan how to anonymise

**Comment by skeating** [comment]
Need to sort data linkage (see 100 DAY project

Need to know what data is required from EHR

**Comment by skeating** [comment]
I have asked Nick about what EHR data is required and contacted Tim R about linking

**Comment by skeating** [comment]
We do now have access to the MRN (see #31) BUT CPET data does not contain this information !!!!

Maybe they maintain a table that maps MRN to CPET_ID ??:

**Comment by clairejblack** [comment]
There is a separate file that contains demographics including the MRN we need to ask Nick or Pietro to upload with the CPET data

**Comment by docsteveharris** [comment]
@skeating can you reach out to Nick Teltow. This doesn't make sense. I wonder if he's shared a deidentified version of the data?

**Comment by skeating** [comment]
CPET keep a separate record that links their number to the MRN
 
So we will be able to link; CPET No -> MRN -> OMOP person_id

BUT I am still waiting for neck to let me know what format their mapping is in
