### ISSUE TITLE
Verify file size limit

### ISSUE THREAD

**Issue by skeating** [UCL-Chimera/bellerophon#43]
Currently we are transferring files from the DSD to a local machine and then to the DSH.
There is a limit to the size of file that can be transferred using this method. 
It will be useful for Claire to know the file limit so she can tailor the data from the ventilators .

**Comment by skeating** [comment]
I managed to transfer 2.5 GB as a single file. I probably wouldn't try anything larger.

**Comment by docsteveharris** [comment]
double check that the browser interface to the DSH does not require Citrix to be enabled
