### ISSUE TITLE
Set up space on the data safe haven

### ISSUE THREAD

**Issue by docsteveharris** [UCL-Chimera/bellerophon#5]
- [x] everyone on CHIMERA will have access
- [x] documentation around how to use
- [x] place for raw data
- [x] mail Jack re third-parties
- [x] agreement from UCLH

**Comment by docsteveharris** [comment]
prob reasonable to start this one before Xmas

**Comment by docsteveharris** [comment]
in conversation with Suzanne Emerton at UCLH JRO. re agreements

**Comment by docsteveharris** [comment]
ready to go just waiting for the contract to upload
can do this from the DSH page

**Comment by skeating** [comment]
Contract from UCLH attached to DSH.

Need @unrulyturnip to sign off on Stage 4 [here](https://liveuclac.sharepoint.com/sites/ISD.IGAdvisoryService/Lists/Cases/Portal.aspx?viewpath=%2Fsites%2FISD%2EIGAdvisoryService%2FLists%2FCases%2FPortal%2Easpx)

**Comment by docsteveharris** [comment]
🍾 all done - thanks!
